metric_mapping = {
"outlet_relerror_length": "mRL",
"outlet_relerror_npipes": "mRP",
"nc_deltacon0": "mD0",
"nc_laplacian_dist": "mLD",
"nc_vertex_edge_distance": "mD",
"kstest_edge_betweenness": "mKE",
"kstest_betweenness": "mKN",
"outlet_relerror_nmanholes": "mRM",
"outlet_relerror_diameter": "mRD",
"outlet_kstest_diameters": "mKD",
"outlet_nse_flow" : "mNQ",
"outlet_kge_flow": "mKQ",
"outlet_relerror_flow": "mRQ",
"outlet_nse_flooding": "mNF",
"outlet_kge_flooding": "mKF",
"outlet_relerror_flooding": "mRF"
}

param_mapping = {
"node_merge_distance" : "pNM",
"outlet_length" : "pOL",
"max_street_length" : "pXS",
"river_buffer_distance" : "pRB",
"chahinian_slope_scaling" : "pSS",
"chahinian_angle_scaling" : "pAS",
"length_scaling" : "pLS",
"contributing_area_scaling" : "pCS",
"chahinian_slope_exponent" : "pSE",
"chahinian_angle_exponent" : "pAE",
"length_exponent" : "pLE",
"contributing_area_exponent" : "pCE",
"max_fr" : "pFR",
"min_v" : "pMV",
"max_v" : "pXV",
"min_depth" : "pMD",
"max_depth" : "pXD",
"precipitation" : "pDP",
}